//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_type
    {
        public long id_material_type { get; set; }
        public string title_material_type { get; set; }
        public Nullable<decimal> percentage_of_material_defects { get; set; }
    }
}
