//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class new_technologiesEntities : DbContext
    {
        private static new_technologiesEntities context;

        public new_technologiesEntities()
            : base("name=new_technologiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static new new_technologiesEntities GetContext()
        {
            if (context == null)
            {
                context = new new_technologiesEntities();
            }
            return context;
        }
    
        public virtual DbSet<material_type> material_type { get; set; }
        public virtual DbSet<partner_type> partner_type { get; set; }
        public virtual DbSet<partners> partners { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<request_status> request_status { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
