//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners()
        {
            this.requests = new HashSet<requests>();
        }
    
        public long id_partner { get; set; }
        public string title_partner { get; set; }
        public long type_partner { get; set; }
        public string director_partner { get; set; }
        public string email_partner { get; set; }
        public string phone_partner { get; set; }
        public string legal_address_partner { get; set; }
        public decimal inn_partner { get; set; }
        public Nullable<decimal> rating_partner { get; set; }
    
        public virtual partner_type partner_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requests> requests { get; set; }

        public decimal GetCost
        {
            get
            {
                var requests = new_technologiesEntities.GetContext().requests.Where(x => x.partner_request == id_partner).ToList();
                decimal cost = 0;

                foreach (var request in requests)
                {
                    cost += request.quantity_request * request.products.min_price_for_partner;
                }

                return cost;
            }
        }
    }
}
