//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class requests
    {
        public long product_request { get; set; }
        public long partner_request { get; set; }
        public int quantity_request { get; set; }
        public long status_request { get; set; }
        public System.DateTime application_date_request { get; set; }
        public bool prepayment_status_request { get; set; }
        public Nullable<int> manufacturing_time_request { get; set; }
        public long id_request { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual products products { get; set; }
        public virtual request_status request_status { get; set; }

        public decimal GetCost
        {
            get
            {
                return quantity_request * products.min_price_for_partner;
            }
        }

        public string GetPartnerType
        {
            get
            {
                var partnerType = new_technologiesEntities.GetContext().partner_type.FirstOrDefault(pt => pt.id_partner_type == partners.type_partner);
                return partnerType.title_partner_type;
            }
        }
    }
}
